apiVersion: v1
kind: ConfigMap
metadata:
  name: pintimeapp-api-prod-nginx-conf
  namespace: pintimeapp
data:
  nginx.conf: |
    user nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        server_tokens   off;
        add_header X-Upstream "01";

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" "$http_x_amzn_trace_id" "$http_x_server_select" "$upstream_response_time" "$upstream_http_x_service_name" "$HOSTNAME"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        gzip  on;
        gzip_disable "MSIE [1-6].(?!.*SV1)";
        client_max_body_size 12M;
        client_body_buffer_size 12M;

        include /etc/nginx/conf.d/*.conf;
    }