apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pintimeapp-api-ingress
  namespace: pintimeapp
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-name: pintimeapp-api-prod-alb
    #alb.ingress.kubernetes.io/group.name: trueapp-nonexpose-cms-prod
    #alb.ingress.kubernetes.io/group.order: '5'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:253647675760:certificate/0fc507dc-1785-4f62-a268-00dabc4dde1a
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    #alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: "/healthz"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '60'
    alb.ingress.kubernetes.io/actions.response-healthz: >
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"200","messageBody":"healthz success text"}}
    alb.ingress.kubernetes.io/success-codes: 200-404
  labels:
    app: pintimeapp-api-prod
spec:
  ingressClassName: alb
  rules:
  - host: pintime-eks.pintimehr.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pintimeapp-api-prod-svc
            port: 
              number: 80
      - path: /healthz
        pathType: Prefix
        backend:
          service:
            name: response-healthz
            port: 
              name: use-annotation