apiVersion: v1
kind: Service
metadata:
  labels:
    app: pintimeapp-api-prod-svc
  #annotations:
  #  alb.ingress.kubernetes.io/healthcheck-path: /api/v1/health/check
  name: pintimeapp-api-prod-svc
  namespace: pintimeapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pintimeapp-api-prod